import time, re, string
import streamlit as st
import pandas as pd
import joblib
from PIL import Image
# main header
st.set_page_config(
    page_title="Klasifikasi Emosi",
    page_icon="favicon.ico",
    layout="centered",
    initial_sidebar_state="auto",
    menu_items={
        'Get Help': None,
        'Report a bug': None,
        'About': "Dibuat oleh Merry Nehemia Nainggolan (D1041161047) Universitas Tanjungpura Pontianak"
    }
)
st.title('Aplikasi Klasifikasi Emotion')
st.subheader('Judul Skripsi : Analisis Kinerja Algoritma Terhadap Klasifikasi Emosi Tweet Berbahasa Indonesia')
## sidebar
with st.sidebar:
    radio1 = st.radio(
        "Pilih Vektorisasi",
        ('TF-IDF', 'Bigram'))
    radio2 = st.radio(
        "Pilih Resampling Data",
        ('Default', 'SMOTE'))
    radio3 = st.radio(
        "Pilih Nilai Parameter",
        ('Default', 'Grid Search'))
    radio4 = st.radio(
        "Pilih Algoritma",
        ('K-Nearest Neighbor', 'Support Vector Machine (RBF)'))
if radio1 == 'TF-IDF':
    vect = joblib.load(open('tf-idf.pkl', 'rb'))
    if radio2 == 'Default' and radio3 == 'Default' and radio4 == 'K-Nearest Neighbor':
        model = joblib.load(open('knn-tfidf.pkl', 'rb'))
        st.success('Model : KNN + TFIDF', icon="✅")
    elif radio2 == 'Default' and radio3 == 'Grid Search' and radio4 == 'K-Nearest Neighbor':
        model = joblib.load(open('knn-grid-tfidf.pkl', 'rb'))
        st.sidebar.info('(N_Neighbors = 38)', icon="ℹ️")
        st.success('Model : KNN + GRID SEARCH + TFIDF', icon="✅")
    elif radio2 == 'SMOTE' and radio3 == 'Default' and radio4 == 'K-Nearest Neighbor':
        model = joblib.load(open('knn-smote-tfidf.pkl', 'rb'))
        st.success('Model : KNN + SMOTE + TFIDF', icon="✅")
    elif radio2 == 'SMOTE' and radio3 == 'Grid Search' and radio4 == 'K-Nearest Neighbor':
        model = joblib.load(open('knn-smote-grid-tfidf.pkl', 'rb'))
        st.sidebar.info('(N_Neighbors = 1)', icon="ℹ️")
        st.success('Model : KNN + SMOTE + GRID SEARCH + TFIDF', icon="✅")
    elif radio2 == 'Default' and radio3 == 'Default' and radio4 == 'Support Vector Machine (RBF)':
        model = joblib.load(open('svm-tfidf.pkl', 'rb'))
        st.success('Model : SVM-RBF + TFIDF', icon="✅")
    elif radio2 == 'Default' and radio3 == 'Grid Search' and radio4 == 'Support Vector Machine (RBF)':
        model = joblib.load(open('svm-grid-tfidf.pkl', 'rb'))
        st.sidebar.info('(C = 10, gamma = 0.1)', icon="ℹ️")
        st.success('Model : SVM-RBF + GRID SEARCH + TFIDF', icon="✅")
    elif radio2 == 'SMOTE' and radio3 == 'Default' and radio4 == 'Support Vector Machine (RBF)':
        model = joblib.load(open('svm-smote-tfidf.pkl', 'rb'))
        st.success('Model : SVM-RBF + SMOTE + TFIDF', icon="✅")
    else:
        model = joblib.load(open('svm-smote-grid-tfidf.pkl', 'rb'))
        st.sidebar.info('(C = 10, gamma = 0.1)', icon="ℹ️")
        st.success('Model : SVM-RBF + SMOTE + GRID SEARCH + TFIDF', icon="✅")
else:
    vect = joblib.load(open('bigram.pkl', 'rb'))
    if radio2 == 'Default' and radio3 == 'Default' and radio4 == 'K-Nearest Neighbor':
        model = joblib.load(open('knn-bigram.pkl', 'rb'))
        st.success('Model : KNN + BIGRAM', icon="✅")
    elif radio2 == 'Default' and radio3 == 'Grid Search' and radio4 == 'K-Nearest Neighbor':
        model = joblib.load(open('knn-grid-bigram.pkl', 'rb'))
        st.sidebar.info('(N_Neighbors = 2)', icon="ℹ️")
        st.success('Model : KNN + GRID SEARCH + BIGRAM', icon="✅")
    elif radio2 == 'SMOTE' and radio3 == 'Default' and radio4 == 'K-Nearest Neighbor':
        model = joblib.load(open('knn-smote-bigram.pkl', 'rb'))
        st.success('Model : KNN + SMOTE + BIGRAM', icon="✅")
    elif radio2 == 'SMOTE' and radio3 == 'Grid Search' and radio4 == 'K-Nearest Neighbor':
        model = joblib.load(open('knn-smote-grid-bigram.pkl', 'rb'))
        st.sidebar.info('(N_Neighbors = 1)', icon="ℹ️")
        st.success('Model : KNN + SMOTE + GRID SEARCH + BIGRAM', icon="✅")
    elif radio2 == 'Default' and radio3 == 'Default' and radio4 == 'Support Vector Machine (RBF)':
        model = joblib.load(open('svm-bigram.pkl', 'rb'))
        st.success('Model : SVM-RBF + BIGRAM', icon="✅")
    elif radio2 == 'Default' and radio3 == 'Grid Search' and radio4 == 'Support Vector Machine (RBF)':
        model = joblib.load(open('svm-grid-bigram.pkl', 'rb'))
        st.sidebar.info('(C = 100, gamma = 0.005)', icon="ℹ️")
        st.success('Model : SVM-RBF + GRID SEARCH + BIGRAM', icon="✅")
    elif radio2 == 'SMOTE' and radio3 == 'Default' and radio4 == 'Support Vector Machine (RBF)':
        model = joblib.load(open('svm-smote-bigram.pkl', 'rb'))
        st.success('Model : SVM-RBF + SMOTE + BIGRAM', icon="✅")
    else:
        model = joblib.load(open('svm-smote-grid-bigram.pkl', 'rb'))
        st.sidebar.info('(C = 10, gamma = 0.005)', icon="ℹ️")
        st.success('Model : SVM-RBF + SMOTE + GRID SEARCH + BIGRAM', icon="✅")

with st.form("my_form", True):
    name = st.text_input("Masukkan teks berbahasa indonesia")
    teks = name.title()
    # preprocessing
    teks = teks.lower()
    teks = teks.replace(r"\n", " ")  # remove enter
    # remove username, URL/link, mention, hashtag
    teks = ' '.join(re.sub("([@#][a-z0-9_]+)|([^0-9a-z \t])|(\w+:\/\/\S+)", " ", teks).split())
    teks = re.sub("((x[a-z0-9]{1,}){1,})", "", teks)  # remove emoji utf-8
    teks = re.sub(r'\d+', ' ', teks)  # remove number **

    # normalisasi kata-kata ke bentuk kata seharusnya
    teks = teks.replace(' adlh ','adalah')
    teks = teks.replace(' aja ',' saja ')
    teks = teks.replace(' aj ',' saja ')
    teks = teks.replace(' ae ',' saja ')
    teks = teks.replace(' agr ',' agar ')
    teks = teks.replace(' ampe ',' sampai ')
    teks = teks.replace(' alhmdllh ',' alhamdulillah ')
    teks = teks.replace(' amn ',' amin ')
    teks = teks.replace(' aamiin ',' amin ')
    teks = teks.replace(' aamiin ',' sama ')
    teks = teks.replace(' aja ',' saja ')
    teks = teks.replace(' aq ',' aku ')
    teks = teks.replace(' ato ',' atau ')
    teks = teks.replace(' ane ',' aku ')
    teks = teks.replace(' bs ',' bisa ')
    teks = teks.replace(' bsa ',' bisa ')
    teks = teks.replace(' bkn ',' bukan ')
    teks = teks.replace(' bpk ',' bapak ')
    teks = teks.replace(' bkn ',' bukan ')
    teks = teks.replace(' bnyk ','banyak')
    teks = teks.replace(' byk ',' banyak ')
    teks = teks.replace(' bgt ',' banget ')
    teks = teks.replace(' bgn ',' bangun ')
    teks = teks.replace(' bhn ',' bahan ')
    teks = teks.replace(' bae ',' saja ')
    teks = teks.replace(' bhay ',' bahaya ')
    teks = teks.replace(' bri ',' beri ')
    teks = teks.replace(' brikan ',' berikan ')
    teks = teks.replace(' breng ',' bareng ')
    teks = teks.replace(' blg ',' bilang ')
    teks = teks.replace(' bet ',' banget ')
    teks = teks.replace(' bett ',' banget ')
    teks = teks.replace(' blm ',' belum ')
    teks = teks.replace(' bsok ',' besok ')
    teks = teks.replace(' btw ',' omong-omong ')
    teks = teks.replace(' bngt ',' banget ')
    teks = teks.replace(' bsk ',' besok ')
    teks = teks.replace(' cb ',' coba ')
    teks = teks.replace(' cba ',' coba ')
    teks = teks.replace(' cmn ',' cuman ')
    teks = teks.replace(' cmn ',' cuma ')
    teks = teks.replace(' cewe ',' cewek ')
    teks = teks.replace(' dngn ',' dengan ')
    teks = teks.replace(' dgn ',' dengan ')
    teks = teks.replace(' dg ',' dengan ')
    teks = teks.replace(' dr ',' dari ')
    teks = teks.replace(' dri ',' dari ')
    teks = teks.replace(' d ',' di ')
    teks = teks.replace(' dlu ',' dulu ')
    teks = teks.replace(' dl ',' dulu ')
    teks = teks.replace(' dkit ',' sedikit ')
    teks = teks.replace(' dpn ',' depan ')
    teks = teks.replace(' dpny ',' depannya ')
    teks = teks.replace(' doank ',' doang ')
    teks = teks.replace(' dtk ',' detik ')
    teks = teks.replace(' dkt ',' dekat ')
    teks = teks.replace(' deket ',' dekat ')
    teks = teks.replace(' dy ',' dia ')
    teks = teks.replace(' dya ',' dia ')
    teks = teks.replace(' doi ',' dia ')
    teks = teks.replace(' dpt ',' dapat ')
    teks = teks.replace(' dmn ',' dimana ')
    teks = teks.replace(' dmna ',' dimana ')
    teks = teks.replace(' dlm ',' dalam ')
    teks = teks.replace(' drtd ',' dari tadi ')
    teks = teks.replace(' emg ','memang')
    teks = teks.replace(' g ',' gak ')
    teks = teks.replace(' gk ',' gak ')
    teks = teks.replace(' gt ',' gitu ')
    teks = teks.replace(' gtu ',' gitu ')
    teks = teks.replace(' gn ',' gini ')
    teks = teks.replace(' gmn ',' bagaimana ')
    teks = teks.replace(' gmna ',' gimana ')
    teks = teks.replace(' gaada ',' tidak ada ')
    teks = teks.replace(' gada ',' tidak ada ')
    teks = teks.replace(' gamau ',' tidak mau ')
    teks = teks.replace(' gausah ',' gak usah ')
    teks = teks.replace(' gabisa ',' gak bisa ')
    teks = teks.replace(' goblog ',' goblok ')
    teks = teks.replace(' gua ',' aku ')
    teks = teks.replace(' gue ',' aku ')
    teks = teks.replace(' gw ',' aku ')
    teks = teks.replace(' gwe ',' aku ')
    teks = teks.replace(' gak ',' tidak ')
    teks = teks.replace(' ga ',' tidak ')
    teks = teks.replace(' gpp ',' tidak apa apa ')
    teks = teks.replace(' hny ',' hanya ')
    teks = teks.replace(' hrs ',' harus ')
    teks = teks.replace(' hepi ',' happy ')
    teks = teks.replace(' ilang ',' hilang ')
    teks = teks.replace(' jwb ',' jawab ')
    teks = teks.replace(' jln ',' jalan ')
    teks = teks.replace(' jgn ',' jangan ')
    teks = teks.replace(' jngn ',' jangan ')
    teks = teks.replace(' jga ',' juga ')
    teks = teks.replace(' jg ',' juga ')
    teks = teks.replace(' jmpt ',' jemput ')
    teks = teks.replace(' jdi ','jadi ')
    teks = teks.replace(' jd ',' jadi ')
    teks = teks.replace(' jbtn ',' jabatan ')
    teks = teks.replace(' jjur ',' jujur ')
    teks = teks.replace(' kmrn ',' kemarin ')
    teks = teks.replace(' kmrin ',' kemarin ')
    teks = teks.replace(' kalo ',' kalau ')
    teks = teks.replace(' klau ',' kalau ')
    teks = teks.replace(' krn ',' karena ')
    teks = teks.replace( 'karna ',' karena ')
    teks = teks.replace(' km ',' kamu ')
    teks = teks.replace(' knp ',' kenapa ')
    teks = teks.replace(' knpa ',' kenapa ')
    teks = teks.replace(' kls ',' kelas ')
    teks = teks.replace(' kpd ',' kepada ')
    teks = teks.replace(' klmpok ',' kelompok ')
    teks = teks.replace(' kl ',' kalau ')
    teks = teks.replace(' klo ',' kalau ')
    teks = teks.replace(' klw ',' kalau ')
    teks = teks.replace(' knl ',' kenal ')
    teks = teks.replace(' kemna ',' kemana ') 
    teks = teks.replace(' kaga ',' tidak ')
    teks = teks.replace(' kek ',' kayak ')
    teks = teks.replace(' kayak ',' seperti ')
    teks = teks.replace(' kepo ',' penasaran ')
    teks = teks.replace(' kcelakan ',' kecelakaan ')
    teks = teks.replace(' ktmu ',' ketemu ')
    teks = teks.replace(' khan ',' kan ')
    teks = teks.replace(' lgsg ',' langsung ')
    teks = teks.replace(' lsg ',' langsung ')
    teks = teks.replace(' lg ',' lagi ')
    teks = teks.replace(' lgi ',' lagi ')
    teks = teks.replace(' lbh ',' lebih ')
    teks = teks.replace(' lma ',' lama ')
    teks = teks.replace(' loe ',' lo ')
    teks = teks.replace(' lo ',' kamu ')
    teks = teks.replace(' lu ',' kamu ')
    teks = teks.replace(' liat ',' lihat ')
    teks = teks.replace(' mrk ',' mereka ')
    teks = teks.replace(' msh ','masih ')
    teks = teks.replace(' mo ',' mau ')
    teks = teks.replace(' mao ',' mau ')
    teks = teks.replace(' mwu ',' mau ')
    teks = teks.replace(' mw ',' mau ')
    teks = teks.replace(' mhn ',' mohon ')
    teks = teks.replace(' mrasa ',' merasa ')
    teks = teks.replace(' moga ',' semoga ')
    teks = teks.replace(' mga ',' semoga ')
    teks = teks.replace(' mski ',' meski ')
    teks = teks.replace(' mgkn ',' mungkin ')
    teks = teks.replace(' masi ',' masih ')
    teks = teks.replace(' mmg ',' memang ')
    teks = teks.replace(' mkn ',' makan ')
    teks = teks.replace(' mnum ',' minum ')
    teks = teks.replace('ny ','nya ')
    teks = teks.replace(' n ',' dan ')
    teks = teks.replace(' nggak ',' tidak ')
    teks = teks.replace(' nnti ',' nanti ')
    teks = teks.replace(' ntr ',' nanti ')
    teks = teks.replace(' org ',' orang ')
    teks = teks.replace(' plg ',' pulang ')
    teks = teks.replace(' pdhl ',' padahal ')
    teks = teks.replace(' pdhal ',' padahal ')
    teks = teks.replace(' pgi ',' pagi ')
    teks = teks.replace(' pgn ',' ingin ')
    teks = teks.replace(' pengen ',' ingin ')
    teks = teks.replace(' pda ',' pada ')
    teks = teks.replace(' pd ',' pada ')
    teks = teks.replace(' pcar ',' pacar ')
    teks = teks.replace(' pdnya ',' padanya ')
    teks = teks.replace(' rspnnya ',' responnya ')
    teks = teks.replace(' rspn ',' respon ')
    teks = teks.replace(' sdh ',' sudah ')
    teks = teks.replace(' sdah ',' sudah ')
    teks = teks.replace(' skrg ',' sekarang ')
    teks = teks.replace(' sbab ',' sebab ')
    teks = teks.replace(' sbbnya ',' sebabnya ')
    teks = teks.replace(' smua ',' semua ')
    teks = teks.replace(' sm ',' sama ')
    teks = teks.replace(' sj ',' saja ')
    teks = teks.replace(' sy ',' saya ')
    teks = teks.replace(' sedng ',' sedang ')
    teks = teks.replace(' sdg ',' sedang ')
    teks = teks.replace(' sampe ',' sampai ')
    teks = teks.replace(' mpe ',' sampai ')
    teks = teks.replace(' sampe2 ',' sampai sampai ')
    teks = teks.replace(' smpe ',' sampai ')
    teks = teks.replace(' syg ',' sayang ')
    teks = teks.replace(' smg ',' semoga ')
    teks = teks.replace(' sbg ',' sebagai ')
    teks = teks.replace(' ssuai ',' sesuai ')
    teks = teks.replace(' scr ',' secara ')
    teks = teks.replace(' skli ',' sekali ')
    teks = teks.replace(' sblmnya ',' sebelumnya ')
    teks = teks.replace(' soalx ',' soalnya ')
    teks = teks.replace(' skrg ',' sekarang ')
    teks = teks.replace(' slmat ',' selamat ')
    teks = teks.replace(' sbb ',' sebab ')
    teks = teks.replace(' sna ',' sana ')
    teks = teks.replace(' smsm ',' sama sama ')
    teks = teks.replace(' sodara ',' saudara ')
    teks = teks.replace(' tdk ',' tidak ')
    teks = teks.replace(' tak ',' tidak ')
    teks = teks.replace(' tdj ',' tidak ')
    teks = teks.replace(' trs ',' terus ')
    teks = teks.replace(' trus ',' terus ')
    teks = teks.replace(' ttp ',' tetap ')
    teks = teks.replace(' ttep ',' tetap ')
    teks = teks.replace(' td ',' tadi ')
    teks = teks.replace(' tp ',' tapi ')
    teks = teks.replace(' tpi ',' tapi ')
    teks = teks.replace(' tmbh ',' tambah ')
    teks = teks.replace(' tmbah ',' tambah ')
    teks = teks.replace(' thn ',' tahun ')
    teks = teks.replace(' tn ',' tanah ')
    teks = teks.replace(' tgg ',' tanggung ')
    teks = teks.replace(' tgl ',' tanggal ')
    teks = teks.replace(' tdr ',' tidur ')
    teks = teks.replace(' twt ',' tweet ')
    teks = teks.replace(' tlong ',' tolong ')
    teks = teks.replace(' trmasuk ',' termasuk ')
    teks = teks.replace(' tlp ',' telpon ')
    teks = teks.replace(' tbtb ',' tiba tiba ')
    teks = teks.replace(' tmn ',' teman ')
    teks = teks.replace(' trnyata ',' ternyata ')
    teks = teks.replace(' tgh ',' tengah ')
    teks = teks.replace(' tkut ',' takut ')
    teks = teks.replace(' utk ',' untuk ')
    teks = teks.replace(' udh ',' sudah ')
    teks = teks.replace(' uda ',' sudah ')
    teks = teks.replace(' udeh ',' sudah ')
    teks = teks.replace(' wwnang ',' wewenang ')
    teks = teks.replace(' wkt ',' waktu ')
    teks = teks.replace(' wlpn ',' walaupun ')
    teks = teks.replace(' w ',' aku ')
    teks = teks.replace(' yg ',' yang ')
    teks = teks.replace(' yudhlh ',' ya sudahlah ')
    teks = teks.replace(' yh ',' ya ')
    #------------------------------------------>
    data = vect.transform([teks])
    predict = model.predict(data)
    hasil_predict = " ".join(predict)
    hasil_proba = model.predict_proba(data)
    submitted = st.form_submit_button("🔎 Klasifikasi")
    if submitted:
        with st.spinner('Sedang melakukan klasifikasi...'):
            time.sleep(2)
        st.write('**Hasil kelas emosinya adalah :**',hasil_predict)
        st.write('**Nilai probabilitas setiap kelas :**')
        df0 = pd.DataFrame(hasil_proba, columns=model.classes_)
        st.dataframe(df0)